### ISSUE TITLE
Team sign missing

### ISSUE THREAD

**Issue by MartinBlazek6** [Podkulova/Final-project#12]
Please add Team name into description so I can see.

**Comment by Podkulova** [comment]
I added the name into description as Team 1

**Comment by MartinBlazek6** [comment]
regarding which PR or where can I see that?

**Comment by Podkulova** [comment]
I thought it should be in the introduction in the Description or should it be somewhere else?

**Comment by MartinBlazek6** [comment]
I see, I was looking for that in readme
